// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLzK3UAQ52ftyMvrSlLcwH4vO_PX9w0Y',
    appId: '1:1054458283085:web:3dea010b7e58227b9f8804',
    messagingSenderId: '1054458283085',
    projectId: 'treattracker-41ccf',
    authDomain: 'treattracker-41ccf.firebaseapp.com',
    storageBucket: 'treattracker-41ccf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0Tn8_MP5-UmMByqPKRE41HPuLvEr9FQ',
    appId: '1:1054458283085:android:9508a01fac1b5f179f8804',
    messagingSenderId: '1054458283085',
    projectId: 'treattracker-41ccf',
    storageBucket: 'treattracker-41ccf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnsjaJ24GJU61hA__Xke6IxttifyLIWBY',
    appId: '1:1054458283085:ios:06787f8e0675b83f9f8804',
    messagingSenderId: '1054458283085',
    projectId: 'treattracker-41ccf',
    storageBucket: 'treattracker-41ccf.appspot.com',
    iosBundleId: 'com.example.candyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnsjaJ24GJU61hA__Xke6IxttifyLIWBY',
    appId: '1:1054458283085:ios:06787f8e0675b83f9f8804',
    messagingSenderId: '1054458283085',
    projectId: 'treattracker-41ccf',
    storageBucket: 'treattracker-41ccf.appspot.com',
    iosBundleId: 'com.example.candyTracker',
  );
}
